import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createClient} from '@supabase/supabase-js';
const url='https://rgjdhajnbwmjoqceeypd.supabase.co',key='sb_publishable_maFGs9599a7NvR_iKwxFUA_bnDLwj03';
const make=()=>createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
const admin=make(),member=make(),anon=make();
const ok=async p=>{const r=await p;assert.equal(r.error,null,r.error?.message);return r.data};
const points=JSON.parse(await readFile('dist/assets/rail-points.json','utf8'));
assert.equal(points.length,10444);assert.equal(new Set(points.map(p=>p.id)).size,10444);assert(points.every(p=>Math.abs(p.lat)<=90&&Math.abs(p.lng)<=180));
await ok(admin.auth.signInWithPassword({email:process.env.TEST_EMAIL,password:process.env.TEST_PASSWORD}));
const session=await ok(admin.auth.getSession());const headers={apikey:key,Authorization:`Bearer ${session.session.access_token}`,'Content-Type':'application/json'};
const qaEmail=`qa-${Date.now()}@example.com`,qaPassword=crypto.randomUUID()+'Ab!1';
const create=await fetch(url+'/functions/v1/manage-users',{method:'POST',headers,body:JSON.stringify({email:qaEmail,password:qaPassword,name:'Verificação temporária',role:'Analista'})});
const created=await create.json();assert.equal(create.status,200,JSON.stringify(created));console.log('QA_USER_ID='+created.id);
await ok(member.auth.signInWithPassword({email:qaEmail,password:qaPassword}));
const row={id:'qa-verification',name:'Verificação temporária',kind:'AMV',lat:-23,lng:-46,yard:'QA',km_entry:1,km_exit:2,line_type:'Singela'};
await ok(member.from('locations').insert(row));await ok(member.from('locations').update({line_type:'Dupla'}).eq('id',row.id));
const audit=await ok(admin.from('audit_logs').select('*').eq('entity_id',row.id));assert(audit.some(x=>x.action==='INSERT'));assert(audit.some(x=>x.action==='UPDATE'));
assert.equal((await ok(member.from('audit_logs').select('*'))).length,0);
const elevate=await member.from('profiles').update({role:'Editor'}).eq('id',created.id);assert(elevate.error);
const ms=(await ok(member.auth.getSession())).session;const denied=await fetch(url+'/functions/v1/manage-users',{method:'POST',headers:{...headers,Authorization:`Bearer ${ms.access_token}`},body:'{}'});assert.equal(denied.status,403);
const bytes=Uint8Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1sAAAAASUVORK5CYII=','base64'));
const path='qa-verification/test.png';await ok(member.storage.from('location-photos').upload(path,bytes,{contentType:'image/png'}));
await ok(member.from('photos').insert({location_id:row.id,path}));const signed=await ok(member.storage.from('location-photos').createSignedUrl(path,60));assert((await fetch(signed.signedUrl)).ok);
const anonRead=await anon.from('locations').select('*');assert(anonRead.error||anonRead.data.length===0);
await ok(member.storage.from('location-photos').remove([path]));await ok(member.from('photos').delete().eq('location_id',row.id));await ok(member.from('locations').delete().eq('id',row.id));
await ok(member.rpc('record_activity',{event:'VIEW_MAP',detail:'QA'}));
await member.auth.signOut();await admin.auth.signOut();console.log('PASS: KMZ, login, creation, RLS, audit, permissions, photo upload/download/delete.');
