import L from 'leaflet';
import {createClient} from '@supabase/supabase-js';
import {validateDocument} from './documents.js';
import {mountOperationMap,mountOperationRecords,recordsForPoint} from './operation.js';
const db=createClient('https://rgjdhajnbwmjoqceeypd.supabase.co','sb_publishable_maFGs9599a7NvR_iKwxFUA_bnDLwj03');
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kinds=['Ponto ferroviário','AMV','Estação','Pátio','Sede'], lines=['Não classificada','Singela','Dupla','Desviada'],roles=['Editor','Analista','Fiscal','Especialista','Coordenador'];
const icons={documents:'<path d="M14 2H5v20h14V7Z M14 2v6h5 M8 12h8 M8 16h8"/>',map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Z M9 3v16 M15 5v16"/>',records:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/>',profile:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',audit:'<path d="m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6Z M8 12l3 3 5-6"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M2 21v-3a7 7 0 0 1 14 0v3M17 5a3 3 0 0 1 0 6M18 15a5 5 0 0 1 4 5"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',present:'<path d="M4 9V4h5M20 9V4h-5M4 15v5h5M20 15v5h-5"/>',exit:'<path d="M9 4v5H4M15 4v5h5M9 20v-5H4M15 20v-5h5"/>',moon:'<path d="M20 14.5A8.5 8.5 0 1 1 9.5 4a7 7 0 0 0 10.5 10.5Z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',signout:'<path d="M15 4h4v16h-4M10 8l-4 4 4 4M6 12h10"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[n]}</svg>`;
let user,profile,base=[],points=[],sbSegments=[],pnPoints=[],operationCatalog,map,operationView,mapFocus,recordFocus,route='map',loadError='';
let navCollapsed=false;
try{navCollapsed=localStorage.getItem('mapa.navCollapsed')==='1'}catch{}
const fmt=n=>Number(n).toLocaleString('pt-BR'), options=(a,v)=>a.map(x=>`<option ${x===v?'selected':''}>${esc(x)}</option>`).join('');
function toast(m){const t=$('#toast');t.textContent=m;t.style.display='block';clearTimeout(t.timer);t.timer=setTimeout(()=>t.style.display='none',4500)}
function fail(e){console.error(e);toast(e.message||'Não foi possível concluir. Tente novamente.')}
async function check(q){const r=await q;if(r.error)throw r.error;return r.data}
async function activity(event,detail=''){try{await check(db.rpc('record_activity',{event,detail}))}catch(e){console.error('Auditoria indisponível',e)}}
function initials(){return profile.name.split(' ').map(s=>s[0]).slice(0,2).join('').toUpperCase()}
function removeMap(){operationView?.destroy();operationView=null;map=null}
function login(){removeMap();$('#app').innerHTML=`<main class="login"><section class="login-art"><img class="logo" src="assets/rumo.svg" alt="Rumo"><div><div class="eyebrow">OPERAÇÕES FERROVIÁRIAS</div><h1>O território.<br>A informação.<br>A operação.</h1><p>A malha e os pontos da operação, conectados em um só lugar.</p></div><small>Mapa de Operações</small></section><section class="login-panel"><div class="login-form"><span class="eyebrow">MAPA DE OPERAÇÕES</span><h2 style="margin-top:18px">Bem-vindo de volta.</h2><p class="muted">Acesse sua conta para continuar.</p><form id="login-form" class="stack"><label>E-mail<input name="email" type="email" autocomplete="username" placeholder="seu.nome@rumolog.com" required></label><label>Senha<input name="password" type="password" autocomplete="current-password" placeholder="Digite sua senha" required></label><p class="error" id="login-error" hidden></p><button class="primary">Entrar</button></form><div class="login-foot">Precisa de acesso? Solicite uma conta ao Editor.</div></div></section></main>`;
$('#login-form').onsubmit=async e=>{e.preventDefault();const btn=$('button',e.target);btn.disabled=true;btn.textContent='Entrando…';try{const f=new FormData(e.target);await check(db.auth.signInWithPassword({email:f.get('email').trim(),password:f.get('password')}));await start();await activity('LOGIN')}catch(err){$('#login-error').hidden=false;$('#login-error').textContent=err.message==='Invalid login credentials'?'E-mail ou senha incorretos.':err.message;btn.disabled=false;btn.textContent='Entrar'}}}
async function loadPoints(){const saved=[];for(let offset=0;;offset+=1000){const batch=await check(db.from('locations').select('*').order('id').range(offset,offset+999));saved.push(...batch);if(batch.length<1000)break}const merged=new Map(base.map(p=>[p.id,{...p,kind:'Ponto ferroviário',line_type:'Não classificada',notes:'',km_entry:null,km_exit:null}]));saved.forEach(p=>merged.set(p.id,{...merged.get(p.id),...p}));points=[...merged.values()];loadError=''}
async function loadReferenceData(){if(operationCatalog)return;const urls=['assets/rail-points.json','assets/rail-sb.json','assets/rail-pns.json','assets/operation/catalog.json'];[base,sbSegments,pnPoints,operationCatalog]=await Promise.all(urls.map(async url=>{const r=await fetch(url);if(!r.ok)throw Error('Não foi possível carregar os dados do mapa.');return r.json()}))}
async function start(){const session=await check(db.auth.getSession());user=session.session?.user;if(!user)return login();const {error:sessionError}=await db.auth.getUser();if(sessionError?.name==='AuthSessionMissingError'){user=null;login();throw Error('Sua sessão foi encerrada. Entre novamente.')}profile=await check(db.from('profiles').select('*').eq('id',user.id).maybeSingle());if(!profile){await db.auth.signOut();login();throw Error('Sua conta ainda não possui acesso. Procure o Editor.')}shell();try{await loadReferenceData();await loadPoints();renderRoute()}catch(e){loadError=e.message;$('.content').innerHTML=`<div class="page card"><h2>Não foi possível carregar o mapa</h2><p>${esc(e.message)}</p><button id="retry">Tentar novamente</button></div>`;$('#retry').onclick=()=>start().catch(fail)}}
function shell(){const nav=[['map','Mapa'],['records','Registros'],['documents','Documentos'],['profile','Meu perfil'],...(profile.role==='Editor'?[['audit','Auditoria'],['users','Usuários']]:[])];const menuLabel=navCollapsed?'Abrir menu':'Recolher menu';$('#app').innerHTML=`<div class="shell${navCollapsed?' nav-collapsed':''}"><aside class="sidebar"><img class="logo" src="assets/rumo.svg" alt="Rumo"><div class="nav-label">MAPA DE OPERAÇÕES</div><nav class="nav">${nav.map(([id,t])=>`<button data-route="${id}" title="${t}">${icon(id)}<span>${t}</span></button>`).join('')}</nav><div class="side-bottom"><div class="row"><div class="avatar" title="${esc(profile.name)}">${esc(initials())}</div><div><div class="user-name">${esc(profile.name)}</div><div class="role">${esc(profile.role)}</div></div></div><button class="signout" title="Sair da conta">${icon('signout')}<span>Sair da conta</span></button></div></aside><header class="topbar"><div class="row topbar-title"><button id="menu-toggle" class="icon-btn" aria-expanded="${!navCollapsed}" aria-label="${menuLabel}" title="${menuLabel}">${icon('menu')}</button><div><h1>Mapa de Operações</h1><div class="sub">Rumo · Gestão do território ferroviário</div></div></div><div class="row topbar-actions"><button id="present-mode" class="with-icon" title="Modo Apresentação" hidden>${icon('present')}<span>Modo Apresentação</span></button><button id="theme-toggle" class="icon-btn"></button><span class="badge">${esc(profile.role)}</span></div></header><main class="content"><div class="loading">Carregando a malha ferroviária…</div></main></div>`;$$('[data-route]').forEach(b=>b.onclick=()=>{route=b.dataset.route;renderRoute()});$('.signout').onclick=logout;$('#menu-toggle').onclick=toggleNav;$('#present-mode').onclick=()=>setPresentation(true);$('#theme-toggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');themeButton()}
function toggleNav(){navCollapsed=!navCollapsed;$('.shell').classList.toggle('nav-collapsed',navCollapsed);const b=$('#menu-toggle'),t=navCollapsed?'Abrir menu':'Recolher menu';b.setAttribute('aria-expanded',!navCollapsed);b.setAttribute('aria-label',t);b.title=t;try{localStorage.setItem('mapa.navCollapsed',navCollapsed?'1':'0')}catch{}}
function themeButton(){const b=$('#theme-toggle');if(!b)return;const dark=document.documentElement.dataset.theme==='dark',t=dark?'Ativar tema claro':'Ativar tema escuro';b.innerHTML=icon(dark?'sun':'moon');b.setAttribute('aria-label',t);b.title=t}
function setTheme(t){document.documentElement.dataset.theme=t;themeButton();if(map)drawPoints()}
async function setPresentation(on){const s=$('.shell');if(!s)return;s.classList.toggle('presenting',on);$('.map-panel')?.classList.remove('open');try{if(on&&!document.fullscreenElement)await document.documentElement.requestFullscreen?.();if(!on&&document.fullscreenElement)await document.exitFullscreen()}catch{}}
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&$('.presenting'))setPresentation(false)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('.presenting')&&!document.fullscreenElement&&!$('#modal').open)setPresentation(false)});
async function logout(){await activity('LOGOUT');await db.auth.signOut({scope:'local'});profile=null;user=null;login()}
function renderRoute(){removeMap();$('#present-mode').hidden=route!=='map';$$('[data-route]').forEach(b=>{b.classList.toggle('active',b.dataset.route===route);b.setAttribute('aria-current',b.dataset.route===route?'page':'false')});if(route==='map')renderMap();if(route==='records')renderRecords();if(route==='profile')renderProfile();if(route==='documents')renderDocuments();if(route==='audit'&&profile.role==='Editor')renderAudit();if(route==='users'&&profile.role==='Editor')renderUsers();activity(({map:'VIEW_MAP',records:'VIEW_RECORDS',profile:'VIEW_PROFILE',documents:'VIEW_DOCUMENTS'})[route]||'VIEW_MAP')}
function newPoint(lat=-15.6,lng=-47.9){openPoint({id:crypto.randomUUID(),name:'',kind:'AMV',lat,lng,yard:'',line_type:'Não classificada',notes:''},true)}
function showMapReference(focus){mapFocus=focus;route='map';renderRoute()}
function renderMap(){operationView=mountOperationMap({L,root:$('.content'),catalog:operationCatalog,points,sbSegments,pnPoints,onPoint:openPoint,onAdd:p=>newPoint(p.lat,p.lng),onMap:m=>{map=m},onRecords:item=>{recordFocus=item;route='records';renderRoute()},onPresentation:setPresentation,focus:mapFocus});mapFocus=null}
function drawPoints(){operationView?.refresh(points)}
function dialog(title,body,tag='REGISTRO') {const d=$('#modal');d.innerHTML=`<div class="modal-head"><div><span class="eyebrow">${esc(tag)}</span><h2>${esc(title)}</h2></div><button class="close" aria-label="Fechar">×</button></div><div class="modal-body">${body}</div>`;$('.close',d).onclick=()=>d.close();if(!d.open)d.showModal();d.onclick=e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}}
function openPoint(p,isNew=false){activity('VIEW_POINT',p.id);dialog(isNew?'Adicionar ponto':p.name,`${p.source_km?`<div class="source-info">Origem: Malha Rumo · <strong>${esc(p.yard)}</strong><br>KM original do arquivo: <strong>${esc(p.source_km)}</strong><br><span class="muted">Valor preservado como recebido; confirme a unidade antes de preencher o AMV.</span></div>`:''}<form id="point-form"><div class="field-grid"><label class="wide">Nome do ponto<input name="name" value="${esc(p.name)}" maxlength="180" required></label><label>Tipo de registro<select name="kind">${options(kinds,p.kind)}</select></label><label>Tipo de linha<select name="line_type">${options(lines,p.line_type)}</select></label><label class="wide">Pátio<input name="yard" value="${esc(p.yard)}" maxlength="180" placeholder="Nome ou sigla do pátio"></label><label>KM de entrada do AMV<input name="km_entry" type="number" step="any" min="0" value="${esc(p.km_entry)}" placeholder="Não informado"></label><label>KM de saída do AMV<input name="km_exit" type="number" step="any" min="0" value="${esc(p.km_exit)}" placeholder="Não informado"></label><label>Latitude<input name="lat" type="number" step="any" min="-90" max="90" value="${p.lat}" required ${p.id.startsWith('kmz-')?'readonly':''}></label><label>Longitude<input name="lng" type="number" step="any" min="-180" max="180" value="${p.lng}" required ${p.id.startsWith('kmz-')?'readonly':''}></label><label class="wide">Observações<textarea name="notes" maxlength="10000" placeholder="Informações sobre este ponto">${esc(p.notes)}</textarea></label></div><p class="error" id="point-error" hidden></p><div class="modal-actions"><button type="button" id="cancel">Cancelar</button><button class="primary">Salvar informações</button></div></form><div class="photos-section"><div class="row between"><h3>Fotos do ponto</h3><label><span class="muted">JPEG, PNG ou WebP · até 10 MB</span><input id="photo-input" type="file" accept="image/jpeg,image/png,image/webp" ${isNew?'disabled':''}></label></div><div id="photos" class="photos"></div><p class="muted" id="photo-status">${isNew?'Salve o ponto para adicionar fotos.':'Carregando fotos…'}</p></div>`);
const pdfReferences=recordsForPoint(operationCatalog,p);
if(pdfReferences.length){const panel=document.createElement('section');panel.className='point-source-context';panel.innerHTML=`<h3>Referências na prancha de operação</h3><p class="muted">Base SIV · ${esc(operationCatalog.sourceDate)}</p>${pdfReferences.map(r=>`<button type="button" data-source-ref="${r.id}">${esc(r.text)}</button>`).join('')}`;$('.modal-body').prepend(panel);panel.querySelectorAll('[data-source-ref]').forEach(b=>b.onclick=()=>{$('#modal').close();showMapReference({type:'pdf',id:b.dataset.sourceRef})})}
const latitude=Number(p.lat),longitude=Number(p.lng);
if(Number.isFinite(latitude)&&Number.isFinite(longitude)&&Math.abs(latitude)<=90&&Math.abs(longitude)<=180){
  const location=document.createElement('div');
  location.className='point-map-link';
  const coordinates=document.createElement('span');
  coordinates.textContent=`Localização: ${latitude.toFixed(6)}, ${longitude.toFixed(6)}`;
  const mapsLink=document.createElement('a');
  mapsLink.className='maps-link';
  mapsLink.textContent='Abrir no Google Maps';
  mapsLink.href=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${latitude},${longitude}`)}`;
  mapsLink.target='_blank';
  mapsLink.rel='noopener noreferrer';
  location.append(coordinates,mapsLink);
  $('#point-form').before(location);
}
$('#cancel').onclick=()=>$('#modal').close();$('#point-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));for(const k of ['lat','lng','km_entry','km_exit'])f[k]=f[k]===''?null:Number(f[k]);if(f.km_entry!==null&&f.km_exit!==null&&f.km_exit<f.km_entry){$('#point-error').hidden=false;$('#point-error').textContent='O KM de saída deve ser maior ou igual ao KM de entrada.';return}const b=$('button.primary',e.target);b.disabled=true;try{await check(db.from('locations').upsert({...f,id:p.id,source_km:p.source_km||'',updated_at:new Date().toISOString()}));await loadPoints();toast('Informações salvas.');if(map)drawPoints();if(route==='records')renderRecords();openPoint(points.find(x=>x.id===p.id))}catch(err){$('#point-error').hidden=false;$('#point-error').textContent=err.message;b.disabled=false}};$('#photo-input').onchange=e=>uploadPhoto(p,e.target.files[0]).catch(fail);if(!isNew)loadPhotos(p).catch(fail)}
async function ensureSaved(p){await check(db.from('locations').upsert({id:p.id,name:p.name,kind:p.kind,yard:p.yard,source_km:p.source_km||'',lat:p.lat,lng:p.lng,line_type:p.line_type,km_entry:p.km_entry,km_exit:p.km_exit,notes:p.notes,updated_at:new Date().toISOString()},{onConflict:'id',ignoreDuplicates:true}))}
async function uploadPhoto(p,file,old){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10485760)throw Error('Escolha uma imagem JPEG, PNG ou WebP de até 10 MB.');const input=$('#photo-input');if(input)input.disabled=true;try{await ensureSaved(p);const path=`${p.id}/${crypto.randomUUID()}.${file.type.split('/')[1]}`;await check(db.storage.from('location-photos').upload(path,file));try{if(old)await check(db.from('photos').update({path}).eq('id',old.id));else await check(db.from('photos').insert({location_id:p.id,path,caption:file.name}));}catch(e){await db.storage.from('location-photos').remove([path]);throw e}if(old){const r=await db.storage.from('location-photos').remove([old.path]);if(r.error)toast('Foto alterada; não foi possível limpar o arquivo anterior.')}toast('Foto salva.');await loadPhotos(p)}finally{if(input){input.disabled=false;input.value=''}}}
async function loadPhotos(p){const photos=await check(db.from('photos').select('*').eq('location_id',p.id).order('created_at'));if(!$('#photos'))return;$('#photo-status').textContent=photos.length?'':'Nenhuma foto adicionada.';const signed=photos.length?await check(db.storage.from('location-photos').createSignedUrls(photos.map(x=>x.path),3600)):[];$('#photos').innerHTML=photos.map((ph,i)=>`<div class="photo"><a href="${esc(signed[i].signedUrl)}" target="_blank" rel="noopener"><img src="${esc(signed[i].signedUrl)}" alt="${esc(ph.caption||'Foto do ponto')}" loading="lazy"></a><div class="row"><button data-replace="${i}">Alterar</button><button class="danger" data-delete="${i}">Excluir</button></div></div>`).join('');$$('[data-replace]').forEach(b=>b.onclick=()=>{const inp=document.createElement('input');inp.type='file';inp.accept='image/jpeg,image/png,image/webp';inp.onchange=()=>uploadPhoto(p,inp.files[0],photos[b.dataset.replace]).catch(fail);inp.click()});$$('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir esta foto do ponto?'))return;b.disabled=true;try{const ph=photos[b.dataset.delete];await check(db.storage.from('location-photos').remove([ph.path]));await check(db.from('photos').delete().eq('id',ph.id));await loadPhotos(p);toast('Foto excluída.')}catch(e){b.disabled=false;fail(e)}})}
function renderRecords(){mountOperationRecords({root:$('.content'),catalog:operationCatalog,points,sbSegments,onPoint:openPoint,onAdd:()=>newPoint(),onMap:showMapReference,focus:recordFocus});recordFocus=null}
function renderProfile(){$('.content').innerHTML=`<div class="page"><div class="page-head"><div><h2>Meu perfil</h2><p class="muted">Seus dados de acesso ao Mapa de Operações.</p></div><button id="profile-logout">Sair</button></div><div class="card profile-card"><div class="row"><div class="avatar">${esc(initials())}</div><div><h3 style="margin-bottom:5px">${esc(profile.name)}</h3><span class="badge">${esc(profile.role)}</span></div></div><form id="profile-form" class="stack"><label>Nome<input name="name" value="${esc(profile.name)}" required maxlength="120"></label><label>E-mail<input value="${esc(profile.email)}" type="email" disabled></label><button class="primary">Salvar perfil</button></form><form id="password-form" class="stack" style="margin-top:30px"><h3>Alterar senha</h3><label>Nova senha<input name="password" type="password" minlength="8" autocomplete="new-password" required></label><label>Confirme a nova senha<input name="confirm" type="password" minlength="8" autocomplete="new-password" required></label><button>Atualizar senha</button></form></div></div>`;$('#profile-logout').onclick=logout;$('#profile-form').onsubmit=async e=>{e.preventDefault();try{await check(db.from('profiles').update({name:new FormData(e.target).get('name').trim()}).eq('id',user.id));await start();toast('Perfil atualizado.')}catch(e){fail(e)}};$('#password-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('password')!==f.get('confirm'))return toast('As senhas não coincidem.');try{await check(db.auth.updateUser({password:f.get('password')}));e.target.reset();toast('Senha atualizada.')}catch(e){fail(e)}}}
async function renderUsers(){$('.content').innerHTML='<div class="page"><div class="loading">Carregando usuários…</div></div>';try{const users=await check(db.from('profiles').select('*').order('name'));$('.content').innerHTML=`<div class="page"><div class="page-head"><div><h2>Usuários</h2><p class="muted">Contas e perfis de acesso da equipe.</p></div><button class="primary" id="new-user">+ Criar conta</button></div><div class="card table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td><span class="badge">${esc(u.role)}</span></td></tr>`).join('')}</tbody></table></div></div>`;$('#new-user').onclick=()=>{dialog('Criar conta',`<form id="user-form" class="stack"><label>Nome<input name="name" required maxlength="120"></label><label>E-mail<input name="email" type="email" required autocomplete="off"></label><label>Perfil<select name="role">${options(roles,'Analista')}</select></label><label>Senha inicial<input name="password" type="password" required minlength="8" autocomplete="new-password"></label><p class="error" id="user-error" hidden></p><button class="primary">Criar conta</button></form>`,'ADMINISTRAÇÃO');$('#user-form').onsubmit=async e=>{e.preventDefault();const b=$('button',e.target);b.disabled=true;try{const body=Object.fromEntries(new FormData(e.target));const {data,error}=await db.functions.invoke('manage-users',{body});if(error?.context?.status===401){$('#modal').close();user=null;await db.auth.signOut({scope:'local'});login();toast('Sua sessão foi encerrada. Entre novamente e crie a conta.');return}if(error||data?.error){let msg=data?.error;try{msg||=(await error.context.json()).error}catch{}throw Error(msg||'Não foi possível criar a conta. Verifique os dados e seu acesso.')}$('#modal').close();toast('Conta criada.');renderUsers()}catch(e){$('#user-error').hidden=false;$('#user-error').textContent=e.message;b.disabled=false}}}}catch(e){fail(e);$('.content').innerHTML='<div class="page error">Não foi possível carregar os usuários.</div>'}}
let auditPage=0;
const actionNames={VIEW_DOCUMENTS:'Consultou documentos',DOWNLOAD_DOCUMENT:'Baixou documento',INSERT:'Criou',UPDATE:'Alterou',DELETE:'Excluiu',LOGIN:'Entrou',LOGOUT:'Saiu',VIEW_MAP:'Abriu o mapa',VIEW_RECORDS:'Consultou registros',VIEW_POINT:'Consultou ponto',VIEW_PROFILE:'Abriu o perfil'};
async function renderAudit(){try{const {data:logs,error,count}=await db.from('audit_logs').select('*',{count:'exact'}).order('created_at',{ascending:false}).range(auditPage*50,auditPage*50+49);if(error)throw error;$('.content').innerHTML=`<div class="page"><div class="page-head"><div><h2>Auditoria</h2><p class="muted">Atividades dos perfis Analista, Fiscal, Especialista e Coordenador.</p></div><button id="audit-refresh">Atualizar</button></div><div class="card">${logs.length?`<div class="table-wrap"><table><thead><tr><th>Data e hora</th><th>Usuário</th><th>Perfil</th><th>Atividade</th><th>Registro</th><th></th></tr></thead><tbody>${logs.map((l,i)=>`<tr><td>${new Date(l.created_at).toLocaleString('pt-BR')}</td><td>${esc(l.actor_name)}</td><td>${esc(l.actor_role)}</td><td>${actionNames[l.action]||esc(l.action)}</td><td>${esc(l.after_data?.name||l.before_data?.name||l.entity_id)||'—'}</td><td><button data-audit="${i}">Detalhes</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhuma atividade registrada ainda.<br><br>As ações dos demais perfis aparecerão aqui.</div>'}<div class="pager"><span>${count} atividades</span><button id="audit-prev" ${auditPage===0?'disabled':''}>Anterior</button><button id="audit-next" ${(auditPage+1)*50>=count?'disabled':''}>Próxima</button></div></div></div>`;$('#audit-refresh').onclick=()=>{auditPage=0;renderAudit()};$('#audit-prev').onclick=()=>{auditPage--;renderAudit()};$('#audit-next').onclick=()=>{auditPage++;renderAudit()};$$('[data-audit]').forEach(b=>b.onclick=()=>{const l=logs[b.dataset.audit];dialog('Detalhes da atividade',`<p>${esc(l.actor_name)} · ${esc(l.actor_role)}</p><p>${esc(actionNames[l.action]||l.action)} · ${new Date(l.created_at).toLocaleString('pt-BR')}</p><h3>Antes</h3><pre class="audit-details">${esc(JSON.stringify(l.before_data,null,2)||'—')}</pre><h3>Depois</h3><pre class="audit-details">${esc(JSON.stringify(l.after_data,null,2)||'—')}</pre>`,'AUDITORIA')})}catch(e){fail(e);$('.content').innerHTML='<div class="page error">Não foi possível carregar a auditoria.</div>'}}
let documentRows=[],documentQuery='';
const fileSize=n=>n>=1048576?`${(n/1048576).toLocaleString('pt-BR',{maximumFractionDigits:1})} MB`:`${Math.ceil(n/1024)} KB`;
async function renderDocuments(){
 $('.content').innerHTML='<div class="page"><div class="loading">Carregando documentos…</div></div>';
 try{
  const rows=[];
  for(let offset=0;;offset+=1000){const batch=await check(db.from('documents').select('*').order('created_at',{ascending:false}).order('id').range(offset,offset+999));rows.push(...batch);if(batch.length<1000)break}
  if(route!=='documents')return;
  documentRows=rows;
  $('.content').innerHTML=`<div class="page"><div class="page-head"><div><h2>Documentos</h2><p class="muted">Mapas, referências e planilhas da operação.</p></div>${profile.role==='Editor'?'<button class="primary" id="upload-documents">+ Adicionar documentos</button>':''}</div><div class="card"><div class="filterbar"><input id="documents-search" aria-label="Buscar documentos" placeholder="Buscar pelo nome do documento" value="${esc(documentQuery)}"></div><p class="muted">PDF e Excel · ${rows.length} documento${rows.length===1?'':'s'}</p><div id="documents-table"></div></div></div>`;
  $('#documents-search').oninput=e=>{documentQuery=e.target.value;documentTable()};
  if($('#upload-documents'))$('#upload-documents').onclick=uploadDocumentsDialog;
  documentTable();
 }catch(e){if(route!=='documents')return;$('.content').innerHTML=`<div class="page card"><h2>Documentos indisponíveis</h2><p class="error">${esc(e.message)}</p><button id="documents-retry">Tentar novamente</button></div>`;$('#documents-retry').onclick=renderDocuments}
}
function documentTable(){
 const rows=documentRows.filter(d=>d.name.toLocaleLowerCase('pt-BR').includes(documentQuery.toLocaleLowerCase('pt-BR')));
 $('#documents-table').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Documento</th><th>Formato</th><th>Tamanho</th><th>Adicionado em</th><th>Ações</th></tr></thead><tbody>${rows.map(d=>`<tr><td class="document-name"><strong>${esc(d.name)}</strong></td><td><span class="badge">${esc(d.format)}</span></td><td>${fileSize(d.size_bytes)}</td><td>${new Date(d.created_at).toLocaleDateString('pt-BR')}</td><td><div class="row"><button data-download-doc="${d.id}">Baixar</button>${profile.role==='Editor'?`<button class="danger" data-remove-doc="${d.id}">Excluir</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum documento encontrado.</div>';
 $$('[data-download-doc]').forEach(b=>b.onclick=async()=>{b.disabled=true;const d=documentRows.find(x=>x.id===b.dataset.downloadDoc);try{
  const blob=await check(db.storage.from('documents').download(d.path));
  const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=d.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
  await activity('DOWNLOAD_DOCUMENT',d.name);
 }catch(e){fail(e)}finally{b.disabled=false}});
 $$('[data-remove-doc]').forEach(b=>b.onclick=async()=>{const d=documentRows.find(x=>x.id===b.dataset.removeDoc);if(!confirm(`Excluir o documento “${d.name}”?`))return;b.disabled=true;try{
  const deleted=await check(db.from('documents').delete().eq('id',d.id).select('id'));if(!deleted.length)throw Error('Documento não excluído. Verifique sua permissão.');
  const {error}=await db.storage.from('documents').remove([d.path]);toast(error?'Documento removido da lista; a limpeza do arquivo ficou pendente.':'Documento excluído.');await renderDocuments();
 }catch(e){b.disabled=false;fail(e)}});
}
function uploadDocumentsDialog(){
 dialog('Adicionar documentos',`<form id="document-form" class="stack"><label>Arquivos PDF ou Excel<input id="document-files" type="file" multiple accept=".pdf,.xls,.xlsx" required></label><p class="muted">Selecione um ou mais arquivos. Limite de 50 MB por documento.</p><div id="document-upload-status" role="status" aria-live="polite"></div><button class="primary">Enviar documentos</button></form>`,'BIBLIOTECA');
 $('#document-form').onsubmit=async e=>{
  e.preventDefault();const files=[...$('#document-files').files];if(!files.length)return;
  try{files.forEach(validateDocument)}catch(err){return fail(err)}
  const form=e.target,btn=$('button',form),input=$('#document-files'),d=$('#modal'),close=$('.close',d);btn.disabled=true;input.disabled=true;close.disabled=true;
  const preventCancel=e=>e.preventDefault();d.addEventListener('cancel',preventCancel);d.onclick=null;
  let successes=0;const errors=[];
  for(let i=0;i<files.length;i++){
   const file=files[i];$('#document-upload-status').textContent=`Enviando ${i+1} de ${files.length}: ${file.name}`;
   const {ext,contentType}=validateDocument(file),path=`${crypto.randomUUID()}.${ext}`;
   try{
    await check(db.storage.from('documents').upload(path,file,{contentType}));
    try{await check(db.from('documents').insert({name:file.name,path,format:ext.toUpperCase(),size_bytes:file.size}))}
    catch(err){await db.storage.from('documents').remove([path]);throw err}
    successes++;
   }catch(err){errors.push(`${file.name}: ${err.message}`)}
  }
  d.removeEventListener('cancel',preventCancel);close.disabled=false;
  await renderDocuments();
  if(errors.length){$('#document-upload-status').innerHTML=`<p>${successes} documento(s) enviado(s).</p><p class="error">${errors.map(esc).join('<br>')}</p><p class="muted">Selecione novamente somente os arquivos que falharam.</p>`;btn.disabled=false;input.disabled=false;input.value=''}
  else{d.close();toast(`${successes} documento(s) adicionado(s).`)}
 };
}
db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'&&user){user=null;login()}});
start().catch(e=>{login();fail(e)});
